AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Layouts/LineLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
